# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "CodeQL"

on:
  workflow_dispatch:

jobs:
  analyze:
    name: Test Job1
    runs-on: ${{ 'ubuntu-latest' }}
    steps:
    - name: Checkout repository 1
      uses: actions/checkout@v4
  test:
    name: Test Job2
    environment: test2
    runs-on: ${{ 'ubuntu-latest' }}
    steps:
    - name: Checkout repository 2
      uses: actions/checkout@v4


